# Generated by Django 3.0.1 on 2019-12-19 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=10)),
                ('openingTime', models.CharField(max_length=5)),
                ('closingTime', models.CharField(max_length=5)),
                ('openingTime2', models.CharField(max_length=5)),
                ('closingTime2', models.CharField(max_length=5)),
                ('website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=8)),
                ('time', models.CharField(max_length=5)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.Bar')),
            ],
        ),
    ]
