# Generated by Django 3.0.1 on 2019-12-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='le quizz test', max_length=200),
            preserve_default=False,
        ),
    ]
